name: 01-building-blocks
on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, !World"
  say-goodbye:
    runs-on: ubuntu-latest
    steps:
       - name: Fail Step
         run: |
          "echo Fail State"
           exit 1      


    
    