name: 03-workflow-runner
on: 
    - pull_request
    - workflow_dispatch
      
jobs:
    show-runner:
      runs-on: windows-latest
      steps:
        - name: Window Runner
          shell: base
          run: runner " $RUNNER_OS "
        - name: Macs Runner
          run: runner " $RUNNER_OS "
