name: 03-workflow-runner
on: 
    - pull_request
    - workflow_dispatch
      
jobs:
    show-runner:
      runs-on: macos-latest
      steps:
        - name: Runner
          run: echo " ${{runner.os}} "
        
